version: 2.1
workflows:
  testing:
    jobs:
      - runner
jobs:
  runner:
    machine: true
    resource_class: terraform_test/sorrycypress
    parallelism: 2
    steps:
      - run: 
          name: Sorry-Cypress Tests
          command: |
              git clone https://$CIRCLECI_TOKEN@github.com/PropertyBrands/rez-qas-lrcypress.git 
              cd rez-qas-lrcypress && git checkout -b API_VI remotes/origin/API_V1
              npm install --force
              sudo npm install -g cy2
              export CYPRESS_API_URL="https://sorrycypress.internalaws.liverez.com:1234"
              npx cy2 run --parallel --record --key lrkey01 --ci-build-id $CIRCLE_BUILD_NUM --project ./ --env configFile=stage_local --spec "cypress/integration/api/**/pn.data.*_spec.js"
              
         
         
