version: 2.1
orbs:
  gh: circleci/github-cli@1.0
jobs: 
  plan:
    docker: 
      - image: alpine/terragrunt
    steps:
      - run:
          name: terragrunt plan
          command: |
            git clone  git@github.com:manish-caylent/Infrastructure_code.git --branch 1.0.1
            if [ "${CIRCLE_BRANCH}" == "staging" ];
            then 
              cd deployments/us-west-2/staging
              terragrunt run-all plan
            fi
            if [ "${CIRCLE_BRANCH}" == "prod" ];
            then 
              echo "it is prod"
              cd deployments/us-west-2/prod 
              terragrunt run-all plan
            fi
      - persist_to_workspace: 
          root: .
          paths:
            - .

  apply:
    docker: 
      - image: alpine/terragrunt
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terragrunt apply
          command: |
            if [ "${CIRCLE_BRANCH}" == "staging" ];
            then 
              cd deployments/us-west-2/staging
              terragrunt run-all apply -auto-approve --terragrunt-non-interactive
            fi
            if [ "${CIRCLE_BRANCH}" == "prod" ];
            then 
              echo "it is prod"
              cd deployments/us-west-2/prod 
              terragrunt run-all apply -auto-approve --terragrunt-non-interactive
            fi
      - persist_to_workspace:
          root: .
          paths: 
            - .

workflows:
  version: 2
  plan_release:
    jobs:
      - plan
      - gh/release:
          notes-file: changelog.md
          tag: 1.0.2
          title: Updated checkout path 
          requires:
            - plan
          context:
            - GITHUB_CREDS
          filters:
            branches:
              only:
                - main
      - hold_apply:
          type: approval
          requires:
            - plan
      - apply:
          requires:
            - hold_apply


   