version: 2.1
workflows:
  testing:
    jobs:
      - Deploy_Stage
      
Deploy_Stage:
    docker: 
      - image: amazon/aws-cli
    steps:
      - run: 
         name: "Push to CodeDeploy"
         command: |
           export $CIRCLE_BUILD_NUM=$(($CIRCLE_BUILD_NUM+1))
           echo $CIRCLE_BUILD_NUM