version: 2.1
workflows:
  testing:
    jobs:
      - Deploy_Stage
jobs:     
  Deploy_Stage:
    docker: 
      - image: amazon/aws-cli
    steps:
      - run: 
         name: "Push to CodeDeploy"
         command: |
           CIRCLE_BUILD=$(($CIRCLE_BUILD_NUM+1))
           echo $CIRCLE_BUILD