version: 2.1
workflows:
  testing:
    jobs:
      - runner
jobs:
  runner:
    machine: true
    max_run_time: 30s
    resource_class: terraform_test/sorrycypress
    steps:
      - run: |
         sudo -i
         mkdir test
         cd test && mkdir test2-pass
         
