version: 2.1
workflows:
  testing:
    jobs:
      - runner
jobs:
  runner:
    machine: true
    resource_class: terraform_test/sorrycypress
    steps:
      - run: |
         mkdir sorrycypress
         cd test && mkdir test1
         
