version: 2.1
jobs: 
  plan:
    docker: 
      - image: alpine/terragrunt
    steps:
      - checkout
      - run:
          name: terragrunt plan
          command: |
            if [ "${CIRCLE_BRANCH}" == "trunk" ];
            then 
              terragrunt run-all plan --terragrunt-non-interactive
              echo "it is working"
      - persist_to_workspace: 
          root: .
          paths:
            - .
  apply:
    docker: 
      - image: alpine/terragrunt
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terragrunt apply
          command: |
            cd deployments/us-west-2/staging
            terragrunt run-all apply -auto-approve --terragrunt-non-interactive
      - persist_to_workspace:
          root: .
          paths: 
            - .

workflows:
  version: 2
  plan_release:
    jobs:
      - plan
      - hold_apply:
          type: approval
          requires:
            - plan
      - apply:
          requires:
            - hold_apply


   