version: 2.1
workflows:
  testing:
    jobs:
      - runner
jobs:
  runner:
    machine: true
    resource_class: terraform_test/sorrycypress
    steps:
      - run: |
         mkdir test_dir
         ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
         git clone git@github.com:manish-caylent/terraform_modules.git
         
         
