version: 2.1
workflows:
  testing:
    jobs:
      - runner
jobs:
  runner:
    machine: true
    resource_class: terraform_test/sorrycypress
    parallelism: 2
    steps:
      - run: 
          name: Sorry-Cypress Tests
          command: |
              git clone https://$CIRCLECI_TOKEN@github.com/PropertyBrands/rez-qas-lrcypress.git 
              cd rez-qas-lrcypress && git checkout -b API_VI remotes/origin/API_V1
              
         
         
