version: 2.1
parameters:
  prod-frontend:
    type: boolean
    default: false
  prod-vpc:
    type: boolean
    default: false
  staging-frontend:
    type: boolean
    default: false
  staging-vpc:
    type: boolean
    default: false
jobs:
  plan-stage-vpc:
    docker:
      - image: alpine/terragrunt
    steps:
      - checkout
      - run:
          name: planning the vpc for stage env
          command: |
            cd deployments/us-west-2/staging/vpc 
            terragrunt run-all plan --terragrunt-non-interactive
      - persist_to_workspace:
          root: .
          paths:
            - .
  apply-stage-vpc:
    docker:
      - image: alpine/terragrunt
    steps:
      - attach_workspace:
          at: .
      - run:
          name: applying the vpc for stage env
          command: |
            cd deployments/us-west-2/staging/vpc 
            terragrunt run-all apply --terragrunt-non-interactive
  plan-prod-vpc:
    docker:
      - image: alpine/terragrunt
    steps:
      - checkout
      - run:
          name: planning the vpc for prod env
          command: |
            cd deployments/us-west-2/prod/vpc 
            terragrunt run-all plan --terragrunt-non-interactive
      - persist_to_workspace:
          root: .
          paths:
            - .
  apply-prod-vpc:
    docker:
      - image: alpine/terragrunt
    steps:
      - attach_workspace:
          at: .
      - run:
          name: applying the vpc for prod env
          command: |
            cd deployments/us-west-2/prod/vpc 
            terragrunt run-all apply --terragrunt-non-interactive
            
workflows:
  stage_vpc:
    when: << pipeline.parameters.staging-vpc >> 
    jobs:
      - plan-stage-vpc
      - apply-stage-vpc:
          requires:
            - plan-stage-vpc
          filters:
            branches:
              only: development
  prod_vpc:
    when: << pipeline.parameters.prod-vpc >>
    jobs:
      - plan-prod-vpc
      - apply-prod-vpc:
          requires:
            - plan-prod-vpc
          filters:
            branches:
              only: development
  