# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "terraformstate-us-west-2"
    encrypt = true
    key     = "./terraform.tfstate"
    region  = "us-west-2"
  }
}
